### ISSUE TITLE
template example error

### ISSUE THREAD

**Issue by hobbyml** [ChrisKnott/Eel#120]
Hi.

I tried template example 06_jinja_templates, on python 3.6. 
Somehow I got following error. could you help to solve problem?

Traceback (most recent call last):
  File "python3.6/site-packages/bottle.py", line 862, in _handle
    return route.call(**args)
  File "python3.6/site-packages/bottle.py", line 1740, in wrapper
    rv = callback(*a, **ka)
  File "python3.6/site-packages/eel/__init__.py", line 158, in _static
    template = _jinja_env.get_template(path[n:])
  File "python3.6/site-packages/jinja2/environment.py", line 830, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "python3.6/site-packages/jinja2/environment.py", line 804, in _load_template
    template = self.loader.load(self, name, globals)
  File "python3.6/site-packages/jinja2/loaders.py", line 113, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "python3.6/site-packages/jinja2/loaders.py", line 187, in get_source
    raise TemplateNotFound(template)

**Comment by ChrisKnott** [comment]
Thanks I'll look into this, I made some small changes to it recently that must have broken it
