### ISSUE TITLE
Images missing with Jinja

### ISSUE THREAD

**Issue by ClayMDMI** [ChrisKnott/Eel#125]
When Jinja is not initialized, I can access images with `<img src="database.png" />`.

However, once Jinja is initialized I can no longer access any images and the console prints an error:

```
Traceback (most recent call last):
  File "...\source\repos\RecordPicker\env\Scripts\bottle.py", line 862, in _handle
    return route.call(**args)
  File "...\source\repos\RecordPicker\env\Scripts\bottle.py", line 1740, in wrapper
    rv = callback(*a, **ka)
  File "...\source\repos\RecordPicker\env\lib\site-packages\eel\__init__.py", line 158, in _static
    template = _jinja_env.get_template(path[n:])
  File "...\source\repos\RecordPicker\env\lib\site-packages\jinja2\environment.py", line 830, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "...\source\repos\RecordPicker\env\lib\site-packages\jinja2\environment.py", line 804, in _load_template
    template = self.loader.load(self, name, globals)
  File "...\source\repos\RecordPicker\env\lib\site-packages\jinja2\loaders.py", line 113, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "...\source\repos\RecordPicker\env\lib\site-packages\jinja2\loaders.py", line 175, in get_source
    contents = f.read().decode(self.encoding)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x89 in position 0: invalid start byte
```

According to [this SO answer](https://stackoverflow.com/a/26042681/9519200), it could be a Python issue where `open()` doesn't support UTF-8, but I am not totally sure.

**Comment by samuelhwilliams** [comment]
Hi @ClayMDMI. Please try updating to eel v0.10.2. I think this should fix your issue. Please let us know if it doesn't.

**Comment by samuelhwilliams** [comment]
@ClayMDMI @ChrisKnott Apologies, it looks like version 0.10.2 hasn't been published to PyPi yet. This will get pushed up soon. Please bear with us. :)

**Comment by ClayMDMI** [comment]
No worries! Thank you all for such a quick response.

**Comment by samuelhwilliams** [comment]
v0.10.2 is available on PyPi now @ClayMDMI. Mind giving that a shot and seeing if it fixes your problems?

**Comment by ClayMDMI** [comment]
v0.10.2 fixes the images and CSS issue! Jinja now looks for other files in the right places. Thank you!

However, it did cause another issue. When I run it without Jinja...
```
eel.init("web")
eel.start("templates/hello.html", size=(800, 500))
```
... it breaks with the error...
```
Traceback (most recent call last):
  File "...\source\repos\RecordPicker\env\Scripts\bottle.py", line 862, in _handle
    return route.call(**args)
  File "...\source\repos\RecordPicker\env\Scripts\bottle.py", line 1740, in wrapper
    rv = callback(*a, **ka)
  File "...\source\repos\RecordPicker\env\lib\site-packages\eel\__init__.py", line 156, in _static
    template_prefix = _jinja_templates + '/'
TypeError: 
    unsupported operand type(s) for +: 'NoneType' and 'str'
```
Looks like `start()` checks `if _jinja_templates != None`, but `_static()` doesn't.

**Comment by samuelhwilliams** [comment]
Nice catch. Fixing this now for v0.10.3 😬

**Comment by ClayMDMI** [comment]
It's always the small things 😅

**Comment by samuelhwilliams** [comment]
v0.10.3 is up now. Please try upgrading (again). :)

**Comment by ClayMDMI** [comment]
That fixed it!

**Comment by samuelhwilliams** [comment]
Lovely. Sorry for the buggy experience. Hope it's smoother sailing from here on out! 👍
