### ISSUE TITLE
AssertationError if no initial call of javascript method in javascript

### ISSUE THREAD

**Issue by slo-ge** [ChrisKnott/Eel#142]
I just checked your React tutorial out. I tried to add a new javascript method, which will be called from Python, but on `eel.init`  python always throws an AssertationError.
`AssertionError: eel.expose() call contains '(' or '='`. But when I call the JavaScript method in the same JavaScript file first- the code works as expected. 

```
function getClipboard(  ) {
}
window.eel.expose( getClipboard, 'get_clipboard' )

// and without the following initial call it leads to the AssertationError.
getClipboard( );
```

So the work around is quite easy, but I don't think it's the desired behavior. 
May I overlooked something. 

best regards.

**Comment by samuelhwilliams** [comment]
Hi @slo-ge. Could you please provide a working example and a not-working example? I'm not following exactly what the problem is for now, but from the error message it looks partly to do with one of Eel's dark secrets in how it parses the functions exposed on the JavaScript side.

**Comment by rpm886** [comment]
I'm having a similar issue. When testing out your example React App `Create-React-App` .
Everything works as expected when running in develop mode out of the "src" directory. However, when running out of the "build" directory I get this error:


Traceback (most recent call last):
  File "/Applications/PyCharm.app/Contents/plugins/python/helpers/pydev/pydevd.py", line 1438, in _exec
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/Users/rpm886/Documents/ZoomRoomsProjects/zoom_test/eel_CRA.py", line 120, in <module>
    start_eel(develop=len(sys.argv) == 2)
  File "/Users/rpm886/Documents/ZoomRoomsProjects/zoom_test/eel_CRA.py", line 79, in start_eel
    eel.init(directory,['.tsx', '.ts', '.jsx', '.js', '.html'])
  File "/Users/rpm886/Documents/ZoomRoomsProjects/zoom_test/venv/lib/python2.7/site-packages/eel/__init__.py", line 106, in init
    assert rgx.findall(r'[\(=]', expose_call) == [], msg
AssertionError: eel.expose() call contains '(' or '='
```
