### ISSUE TITLE
Can't use eel inside/with a class

### ISSUE THREAD

**Issue by abovetheairwaves** [ChrisKnott/Eel#180]
If you use Eel inside of a class, and are attempting to use class methods as exposed functions with the `@eel.expose` decorator, you receive an error

> Traceback (most recent call last):
>  File "src\gevent\greenlet.py", line 716, in gevent._greenlet.Greenlet.run
> File "C:\Python27\lib\site-packages\eel\__init__.py", line 241, in _process_message
>    return_val = _exposed_functions[message['name']](*message['args'])
> TypeError: server_info() takes exactly 1 argument (0 given)
> 2019-08-17T05:52:30Z <Greenlet "Greenlet-0" at 0x3179c68: _process_message({u'args': [], u'call': 1.4319639678614375, u'name', <geventwebsocket.websocket.WebSocket object at 0x0)> failed with TypeError

I've addressed this by making the following changes to `__init__.py`:

1. Add a key named `class_instance` with a value of `None` to the `_start_args` dict.

```python
_start_args = {
    'mode':             'chrome',                   # What browser is used
    'host':             'localhost',                # Hostname use for Bottle server
    'port':             8000,                       # Port used for Bottle server (use 0 for auto)
    'block':            True,                       # Whether start() blocks calling thread
    'jinja_templates':  None,                       # Folder for jinja2 templates
    'cmdline_args':     ['--disable-http-cache'],   # Extra cmdline flags to pass to browser start
    'size':             None,                       # (width, height) of main window
    'position':         None,                       # (left, top) of main window
    'geometry':         {},                         # Dictionary of size/position for all windows
    'close_callback':   None,                       # Callback for when all windows have closed
    'app_mode':         True,                       # (Chrome specific option)
    'all_interfaces':   False,                      # Allow bottle server to listen for connections on all interfaces
    'disable_cache':    True,                       # Sets the no-store response header when serving assets
    'class_instance':   None,                       # Allow a class instance (i.e. self) to be passed to exposed functions	
}
```

2. Add a check for `_start_args['class_instance']` to the `_process_message` function, and prepend `_start_args['class_instance']` to the function call, if it not `None`.

```python
def _process_message(message, ws):
    global _start_args
    if 'call' in message:
        if _start_args['class_instance'] is not None:
		    return_val = _exposed_functions[message['name']](_start_args['class_instance'], *message['args'])
        else:
		    return_val = _exposed_functions[message['name']](*message['args'])
        _repeated_send(ws, _safe_json({ 'return': message['call'],
                                        'value': return_val  }))
    elif 'return' in message:
        call_id = message['return']
        if call_id in _call_return_callbacks:
            callback = _call_return_callbacks.pop(call_id)
            callback(message['value'])
        else:
            _call_return_values[call_id] = message['value']
    else:
        print('Invalid message received: ', message)
```
Then, when eel is used inside of a class, and is referencing class methods for exposed functions, you can start eel with `class_instance=self` as an option to allow those methods to work properly.

**Comment by samuelhwilliams** [comment]
Hi @abovetheairwaves, thanks for sharing this.

I'm not sure this is an interface that I want to support at first impressions, but I'd love if you could share your use-case for wanting to use Eel with classes so that we can maybe hash out together if it's something I should change my mind on.
