### ISSUE TITLE
A syntax error of  Eel/eel/browsers.py

### ISSUE THREAD

**Issue by tuerky** [ChrisKnott/Eel#19]
```Traceback (most recent call last):
  File "/Eel-master/examples/01 - hello_world/hello.py", line 12, in <module>
    eel.start('hello.html', size=(300, 200))    # Start
  File "/Eel-master/eel/__init__.py", line 71, in start
    brw.open(start_urls, options)
  File "/Eel-master/eel/browsers.py", line 13, in open
    sps.Popen([chrome_path, '--disable-gpu', '--app=%s' % url] + options['chromeFlags'])
TypeError: can only concatenate list (not "str") to list
```

```
13   sps.Popen([chrome_path, '--disable-gpu', '--app=%s' % url] + options['chromeFlags'])
```

**Comment by ChrisKnott** [comment]
@tuerky Sorry, there was a mistake in the default value for 'chromeFlags', it was fixed here https://github.com/ChrisKnott/Eel/commit/b87c454e1023e4a41cc6cdd88ce3cae4528cd0b9#diff-1484bbbb73640b7757d93097537fecc4

It should work now

**Comment by tuerky** [comment]
thx
