### ISSUE TITLE
Python2+Linux environment fail

### ISSUE THREAD

**Issue by marcorosa** [ChrisKnott/Eel#36]
Using Linux and Python2 raises an error:
```
Traceback (most recent call last):
  File "run.py", line 99, in <module>
    eel.start('main.html', size=(650, 612))
  File "/home/marco/git/auto-py-to-exe/venv/local/lib/python2.7/site-packages/eel/__init__.py", line 84, in start
    brw.open(start_urls, options)
  File "/home/marco/git/auto-py-to-exe/venv/local/lib/python2.7/site-packages/eel/browsers.py", line 8, in open
    chrome_path = find_chrome()
  File "/home/marco/git/auto-py-to-exe/venv/local/lib/python2.7/site-packages/eel/browsers.py", line 32, in find_chrome
    return find_chrome_linux()
  File "/home/marco/git/auto-py-to-exe/venv/local/lib/python2.7/site-packages/eel/browsers.py", line 50, in find_chrome_linux
    chrome = shu.which(name)
AttributeError: 'module' object has no attribute 'which'
```
This is due to the fact that `which` is not in `shutil` module for Python 2 (or is not anymore)

**Comment by ChrisKnott** [comment]
As mentioned on your PR, I went with #34 which should fix this. I will make the required changes today. Thanks again for your interest and contribution.
