### ISSUE TITLE
Not able to build distributable binary with PyInstalle

### ISSUE THREAD

**Issue by amitpathania** [ChrisKnott/Eel#442]
**Describe the problem**
I am trying to build distributable binary with PyInstaller. However, when  I am running python -m eel [your_main_script] [your_web_folder], I am getting following error.  My main script and all files are working fine when I am executing it from command line but I am getting error when creating distributable.  

**Error snippet(s)**
Here is some code that can be easily used to reproduce the problem or understand what I need help with.
2590 INFO: Processing pre-safe import module hook urllib3.packages.six.moves from '/home/site1/.local/lib/python3.6/site-packages/PyInstaller/hooks/pre_safe_import_module/hook-urllib3.packages.six.moves.py'.
Traceback (most recent call last):
  File "<string>", line 2, in <module>
  File "/home/site1/.local/lib/python3.6/site-packages/urllib3/__init__.py", line 7, in <module>
    import logging
  File "/home/site1/.local/lib/python3.6/site-packages/logging/__init__.py", line 618
    raise NotImplementedError, 'emit must be implemented '\
                             ^
SyntaxError: invalid syntax
Error in sys.excepthook:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/apport_python_hook.py", line 72, in apport_excepthook
    from apport.fileutils import likely_packaged, get_recent_crashes
  File "/usr/lib/python3/dist-packages/apport/__init__.py", line 5, in <module>
    from apport.report import Report
  File "/usr/lib/python3/dist-packages/apport/report.py", line 30, in <module>
    import apport.fileutils
  File "/usr/lib/python3/dist-packages/apport/fileutils.py", line 25, in <module>
    from apport.packaging_impl import impl as packaging
  File "/usr/lib/python3/dist-packages/apport/packaging_impl.py", line 24, in <module>
    import apt
  File "/usr/lib/python3/dist-packages/apt/__init__.py", line 26, in <module>
    from apt.package import Package
  File "/usr/lib/python3/dist-packages/apt/package.py", line 24, in <module>
    import logging
  File "/home/site1/.local/lib/python3.6/site-packages/logging/__init__.py", line 618
    raise NotImplementedError, 'emit must be implemented '\
                             ^
SyntaxError: invalid syntax

Original exception was:
Traceback (most recent call last):
  File "<string>", line 2, in <module>
  File "/home/site1/.local/lib/python3.6/site-packages/urllib3/__init__.py", line 7, in <module>
    import logging
  File "/home/site1/.local/lib/python3.6/site-packages/logging/__init__.py", line 618
    raise NotImplementedError, 'emit must be implemented '\
                             ^
SyntaxError: invalid syntax
pre-safe-import-module hook failed, needs fixing.
**Desktop (please complete the following information):**
 - OS: [UBUNTU]
 - Browser [chrome]
 - Version [CHROMIUM]

**Comment by rahmatagungj** [comment]
Are you using python3? if so, try to check the logging module again because in python3 the module sometimes does not run successfully.

**Comment by amitpathania** [comment]
Yes, I'm using python3. There was some issues building my code using eel and pyinstaller package  "python3 -m eel logic.py front --onefile". 
However, resolved the issue by using following command:  pipenv run python3 -m eel logic.py front --onefile
