### ISSUE TITLE
Unable to find Electron app/Cannot find module.

### ISSUE THREAD

**Issue by cutethingg** [ChrisKnott/Eel#456]
### Hello! I'm attempting to use Electron with Eel in the latest versions. 

**The 'mode='electron'' option only yielded me this:**

**Script:**

```
import eel
eel.init('web')
eel.start('index.html', size=(800, 600), block=False, mode='electron')
while True:
    eel.sleep(10)
```
**Error:**
```
Traceback (most recent call last):
  File "C:\Users\User\AppData\Local\Packages\CanonicalGroupLimited.UbuntuonWindows_79rhkp1fndgsc\LocalState\rootfs\root\nexit\new.py", line 7, in <module>
    eel.start('index.html', size=(800, 600), block=False, mode='electron')
  File "C:\Users\User\AppData\Local\Programs\Python\Python39-32\lib\site-packages\eel\__init__.py", line 158, in start
    show(*start_urls)
  File "C:\Users\User\AppData\Local\Programs\Python\Python39-32\lib\site-packages\eel\__init__.py", line 186, in show
    brw.open(start_urls, _start_args)
  File "C:\Users\User\AppData\Local\Programs\Python\Python39-32\lib\site-packages\eel\browsers.py", line 59, in open
    path = browser_module.find_path()
  File "C:\Users\User\AppData\Local\Programs\Python\Python39-32\lib\site-packages\eel\electron.py", line 18, in find_path
    return os.path.join(bat_path, r'..\node_modules\electron\dist\electron.exe')
  File "C:\Users\User\AppData\Local\Programs\Python\Python39-32\lib\ntpath.py", line 78, in join
    path = os.fspath(path)
TypeError: expected str, bytes or os.PathLike object, not NoneType
```

### I assumed the "NoneType" was from the lack of a path to my electron installation, so I **attempted a custom directory:**

**Script:**
```
import eel
eel.init('web')
eel.start('index.html', size=(800, 600), block=False, mode='custom', cmdline_args=['node_modules/electron/dist/electron.exe', '.'])
while True:
    eel.sleep(10)
```
**The error now came in a popup alert box:** ([screenshot](https://imgur.com/J1S5CiL))
```
ERROR LAUNCHING APP

Unable to find Electron app at
C:\Users\User\AppData\Local\Packages\CanonicalGroupLimited.UbuntuonWindow...\nexit

Cannot find module
'C:\Users\User\AppData\Local\Packages\CanonicalGroupLimited.UbuntuonWindow...\main.js'.
Please verify that the package.json has a valid "main" entry
```

### Any input is appreciated, this is a wonderful little library and I only hope to see it grow!

**Here's my directory tree:**

- /Nexit/
    - /node_modules/
        - (all other node modules)  
        - /electron/
            - /dist/
                - electron.exe
    - /web/
        - main.html
        - main.js
        - package.json
    - script.py

My package.json:
```
{
  "name": "nexit",
  "version": "0.0.0",
  "main": "main.js",
  "devDependencies": {
    "electron": "^2.0.0"
  }
}
```
My main.js:
```
console.log("Hello world!");
const electron = require('electron')
const app = electron.app
const BrowserWindow = electron.BrowserWindow

let mainWindow

function createWindow () {
  mainWindow = new BrowserWindow({width: 800, height: 600})
  mainWindow.loadURL('http://localhost:8000/main.html');
  mainWindow.on('closed', function () {
    mainWindow = null
  })
}

app.on('ready', createWindow)

app.on('window-all-closed', function () {
  app.quit()
});

app.on('activate', function () {
  if (mainWindow === null) {
    createWindow()
  }
})

```
My HTML:
```
<!DOCTYPE html>
<html lang="en">
    <head>
	    <meta charset="UTF-8">
		<title>Nexit</title>
		<script type="text/javascript" src="/eel.js"></script>
		<script type="text/javascript" src="main.js"></script>
		<script>
		    eel.expose(jav);
			function jav(a, b) {
			    console.log(a + b);
			}
		</script>
<head></head>
<body><p>text</p></body>
</html>
```

**SPECS:**
 - OS: Windows 10
 - Python v: 3.9.0
 - Eel v: 0.14.0

**Comment by cutethingg** [comment]
Here's the error screenshot if you don't want to click the imgr link:

![error](https://user-images.githubusercontent.com/79818326/109598996-4b97f180-7acf-11eb-8abf-5283f82f32b8.PNG)

**Comment by cutethingg** [comment]
My electron setup was completely wrong here, if you're having similar problems setting up electron with python, check out **[this](https://www.techiediaries.com/python-electron-tutorial/)** link.

Thank you for still supporting the Eel library!
