### ISSUE TITLE
React Demo not working

### ISSUE THREAD

**Issue by elibroftw** [ChrisKnott/Eel#575]
**Eel version**
Latest

**Describe the bug**

PS C:\Users\maste\Documents\GitHub\r2-t2> python .\eel.py
Traceback (most recent call last):
  File "C:\Users\maste\Documents\GitHub\r2-t2\eel.py", line 8, in <module>
    import eel
  File "C:\Users\maste\Documents\GitHub\r2-t2\eel.py", line 14, in <module>
    @eel.expose  # Expose function to JavaScript
AttributeError: partially initialized module 'eel' has no attribute 'expose' (most likely due to a circular import)

**To Reproduce**
1. `pip install eel`
2. Download `https://github.com/ChrisKnott/Eel/blob/master/examples/07%20-%20CreateReactApp/eel_CRA.py`
3. Run it (optionally have React files)

**Expected behavior**
It should work

**Desktop (please complete the following information):**
 - OS: Windows 10

**Additional context**

**Comment by piccinnigius** [comment]
Hi! 
i've fixed it by including:
```
<!-- Load eel.js from the port specified in the eel.start options -->
  <script type="text/javascript" src="http://localhost:<your_python_host_port>/eel.js"></script>
```

in `head` of your `public/index.html` file.

Hope it helps!
