### ISSUE TITLE
Hi! I have some errors with eel.js

### ISSUE THREAD

**Issue by Bomjdeveloper** [ChrisKnott/Eel#599]
**Describe the problem**
I conect eel.js. But browser show me some errors.
This error:
Uncaught TypeError: Cannot read properties of undefined (reading 'length')
    at Object._mock_py_functions (eel.js:35:46)
    at Object._init (eel.js:107:13)
    at eel.js:165:5
**Code snippet(s)**
Here is some code that can be easily used to reproduce the problem or understand what I need help with.

- [ ] I know that if I don't provide sample code that allows someone to quickly step into my shoes, I may not get the help I want or my issue may be closed.

```python
import eel

...
```

```html
<html>
   ...
</html>
```

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Comment by ZJUAlexChen** [comment]
I got the same issue too, did u fix it?

**Comment by dstricks** [comment]
I need more information to help. Can you start by providing some system information:
 - OS: [e.g. Windows 10 x64, Linux Ubuntu, macOS 12]
 - Browser: [e.g. Chrome 108.0.5359.99 (Official Build) (64-bit), Safari 16, Firefox 107.0.1]
 - Python Distribution: [e.g. Python.org 3.9, Anaconda3 2021.11 3.9, ActivePython 3.9]

Also, do you have small example code snippets which can reproduce this issue?
